{"name": "test_006_login_out_failed[json_data0]", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <testcase.test02_login_out.TestLogin_out object at 0x10c75e190>\njson_data = {'token': '11d7ac5b4f242e4bfaabc632009090c1a13fdc49d60ec81535c7b472b899b952a13fdc49d60ec81535c7b472b899b952a13fdc49d60ec81535c7b472b899b952a13fdc49d60ec81535c7b472b899b952'}\n\n    @allure.severity(allure.severity_level.NORMAL)\n    # 获取json文件中的第i条测试用例data数据\n    @pytest.mark.parametrize(\"json_data\", get_json_data(6, \"login_out_data\"))\n    # 数据异常-token过长\n    def test_006_login_out_failed(self, json_data):\n        # 获取token数据\n        token = get_token()\n        # 将token数据赋值给json_data[\"token\"]\n        json_data[\"token\"] = token + json_data[\"token\"]\n        # 调用退出登录接口完成退出，json_data为传入的请求体内容\n        response = self.login_out_api.login_out(json_data)\n        # 断言\n>       assert_login_out.failed_login_out(response)\n\ntestcase/test02_login_out.py:105: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [200]>\n\n    def failed_login_out(response):\n        # 断言状态码\n        assert 200 == response.status_code\n        # 断言业务状态\n>       assert not response.json().get(\"status\")\nE       AssertionError\n\nassert_hww/assert_login_out.py:16: AssertionError"}, "attachments": [{"name": "log", "source": "79c744ad-4be8-41af-a10d-1be12c520627-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "json_data", "value": "{'token': 'a13fdc49d60ec81535c7b472b899b952a13fdc49d60ec81535c7b472b899b952a13fdc49d60ec81535c7b472b899b952a13fdc49d60ec81535c7b472b899b952'}"}], "start": 1710474340511, "stop": 1710474341267, "uuid": "4ade1def-c1c1-459d-b041-8c63f358f7a9", "historyId": "0788017b651ff6a522987213c0eb71ba", "testCaseId": "0f3b296cab5e2fe01d8b9ef815f8ab9a", "fullName": "testcase.test02_login_out.TestLogin_out#test_006_login_out_failed", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test02_login_out"}, {"name": "subSuite", "value": "TestLogin_out"}, {"name": "host", "value": "hkdeMacBook-Pro"}, {"name": "thread", "value": "74463-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test02_login_out"}]}